"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
#import ez_setup
#ez_setup.use_setuptools()
import sys
from setuptools import setup

APP = ['pasziansz.py']
DATA_FILES = ['assets', 'settings.json']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

mainscript = 'pasziansz.py'

if sys.platform == 'darwin':
     extra_options = dict(
         setup_requires=['py2app'],
         app=[mainscript],
         # Cross-platform applications generally expect sys.argv to
         # be used for opening files.
         options=dict(py2app=dict(argv_emulation=True)),
    )
elif sys.platform == 'win32':
     extra_options = dict(
         setup_requires=['py2exe'],
         app=[mainscript],
    )
else:
     extra_options = dict(
         # Normally unix-like platforms will use "setup.py install"
         # and install the main script as such
         scripts=[mainscript],
    )

setup(
    name="Pasziansz",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS}
)